/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nava.maasar;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author j713n
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 248, 210));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search For Report By Member Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Search For Report By Date:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Enter Date (YYYY-MM-DD)");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Enter Last Name of Member");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Go Home");
        jButton3.setToolTipText("Go Back To The Home Page");
        jButton3.setName("GoHome_Button"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tithe Date", "First Name", "Last Name", "Cash Amt", "Credit/Debit Amt", "Check Amt", "Tithe Amt", "Offering Amt", "Pro Temple Amt", "Other Amt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 153));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    //Method for Go Home button
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    //Search button for date search
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String textfieldText = (String) jTextField1.getText();
        System.out.println(textfieldText);
        getDatabaseDataDate(textfieldText);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String textfieldText = (String) jTextField2.getText();
        System.out.println(textfieldText);
        getDatabaseDataLastName(textfieldText);
    }//GEN-LAST:event_jButton2ActionPerformed

    //Fetch data from database using date
    private void getDatabaseDataDate(String date) {
                //data fields to be pulled from tithe table
                String selectData = "titheDate, first_name, last_name, cash_amount, creditOrDebit_amount, " +
                        "check_amount, tithe_amount, offering_amount, proTemple_amount, other_amount";
                String sql1 = "SELECT " + selectData + " FROM tithe";
                String sql2 = " WHERE date(titheDate) = '";
                String sql3 = date;
                String sql = sql1 + sql2 + sql3 + "'";
                Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		try {
                    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                    String connURL = "jdbc:mysql://localhost:3306/***DATABASE NAME GOES HERE"; //DEFAULT MYSQL CONFIG SHOWN
                    String user = "***USERNAME GOES HERE"; //DEFAULT MYSQL USER - root
                    String pwd = "***PASSWORD GOES HERE";
                    conn = DriverManager.getConnection(connURL, user, pwd);
                    stmt = conn.createStatement();		
                    rs = stmt.executeQuery(sql);
                    
                    //For use in ResultSet (rs) while loop
                    int i = 0;
                    int j = 0;
                    //Add data as each row in table
                    while (rs.next()) {
                        Date date1 = rs.getDate("titheDate");
                        DateFormat dateFormat = new SimpleDateFormat("mm-dd-yyyy hh:mm:ss");  
                        String strDate = dateFormat.format(date1);
                        jTable1.setValueAt(strDate, i, j); j++;
                        
                        String fname = rs.getString("first_name");
                        jTable1.setValueAt(fname, i, j); j++;
                        
                        String lname = rs.getString("last_name");
                        jTable1.setValueAt(lname, i, j); j++;
                        
                        double cAmt = rs.getDouble("cash_amount");
                        jTable1.setValueAt(cAmt, i, j); j++;
                        
                        double cODAmt = rs.getDouble("creditOrDebit_amount");
                        jTable1.setValueAt(cODAmt, i, j); j++;
                        
                        double chAmt = rs.getDouble("check_amount");
                        jTable1.setValueAt(chAmt, i, j); j++;
                        
                        double tAmt = rs.getDouble("tithe_amount");
                        jTable1.setValueAt(tAmt, i, j); j++;
                        
                        double offAmt = rs.getDouble("offering_amount");
                        jTable1.setValueAt(offAmt, i, j); j++;
                        
                        double pTAmt = rs.getDouble("proTemple_amount");
                        jTable1.setValueAt(pTAmt, i, j); j++;
                        
                        double oAmt = rs.getDouble("other_amount");
                        jTable1.setValueAt(oAmt, i, j);
                        i++;
                        j = 0;
                    }

		} catch(SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException e) {
			System.out.println("Could not add entries into database...");

		}
		
			try {
				rs.close();
				stmt.close();
				conn.close();
			}
			catch (SQLException | NullPointerException e) {
				// TODO Auto-generated catch block
				
			}

		System.out.println("Entries pulled from database.");
        }
        
        
    //Fetch data from database using date
    private void getDatabaseDataLastName(String name) {
                //data fields to be pulled from tithe table
                String selectData = "titheDate, first_name, last_name, cash_amount, creditOrDebit_amount, " +
                        "check_amount, tithe_amount, offering_amount, proTemple_amount, other_amount";
                String sql1 = "SELECT " + selectData + " FROM tithe";
                String sql2 = " WHERE last_name = '";
                String sql3 = name;
                String sql = sql1 + sql2 + sql3 + "'";
                Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		try {
                    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                    String connURL = "jdbc:mysql://localhost:3306/***DATABASE NAME GOES HERE"; //DEFAULT MYSQL CONFIG SHOWN
                    String user = "***USERNAME GOES HERE"; //DEFAULT MYSQL USER - root
                    String pwd = "***PASSWORD GOES HERE";
                    conn = DriverManager.getConnection(connURL, user, pwd);
                    stmt = conn.createStatement();		
                    rs = stmt.executeQuery(sql);
                    
                    //For use in ResultSet (rs) while loop
                    int i = 0;
                    int j = 0;
                    //Add data as each row in table
                    while (rs.next()) {
                        Date date1 = rs.getDate("titheDate");
                        DateFormat dateFormat = new SimpleDateFormat("mm-dd-yyyy hh:mm:ss");  
                        String strDate = dateFormat.format(date1);
                        jTable1.setValueAt(strDate, i, j); j++;
                        
                        String fname = rs.getString("first_name");
                        jTable1.setValueAt(fname, i, j); j++;
                        
                        String lname = rs.getString("last_name");
                        jTable1.setValueAt(lname, i, j); j++;
                        
                        double cAmt = rs.getDouble("cash_amount");
                        jTable1.setValueAt(cAmt, i, j); j++;
                        
                        double cODAmt = rs.getDouble("creditOrDebit_amount");
                        jTable1.setValueAt(cODAmt, i, j); j++;
                        
                        double chAmt = rs.getDouble("check_amount");
                        jTable1.setValueAt(chAmt, i, j); j++;
                        
                        double tAmt = rs.getDouble("tithe_amount");
                        jTable1.setValueAt(tAmt, i, j); j++;
                        
                        double offAmt = rs.getDouble("offering_amount");
                        jTable1.setValueAt(offAmt, i, j); j++;
                        
                        double pTAmt = rs.getDouble("proTemple_amount");
                        jTable1.setValueAt(pTAmt, i, j); j++;
                        
                        double oAmt = rs.getDouble("other_amount");
                        jTable1.setValueAt(oAmt, i, j);
                        i++;
                        j = 0;
                    }

		} catch(SQLException | InstantiationException | IllegalAccessException | ClassNotFoundException e) {
			System.out.println("Could not add entries into database...");

		}
		
			try {
				rs.close();
				stmt.close();
				conn.close();
			}
			catch (SQLException | NullPointerException e) {
				// TODO Auto-generated catch block
				
			}

		System.out.println("Entries pulled from database.");
        }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
